<?php

namespace CakephpTwilio\Test\TestCase\Model;

use Cake\TestSuite\TestCase;
use CakephpTwilio\Model\Message;

class MessageTest extends TestCase
{
    protected $message;

    protected $testMessage = [
        'to' => '+4100000000',
        'from' => 'SenderName',
        'body' => 'SMS message body'
    ];

    /**
     *
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->message = new Message($this->testMessage['to'], $this->testMessage['body'], $this->testMessage['from']);
    }

    /**
     *
     */
    public function testMessageClass()
    {
        $this->assertInstanceOf(Message::class, $this->message);
    }

    /**
     *
     */
    public function testMessageData()
    {
        $this->assertEquals($this->testMessage['to'], $this->message->getTo());
        $this->assertEquals($this->testMessage['from'], $this->message->getFrom());
        $this->assertEquals($this->testMessage['body'], $this->message->getBody());
    }
}
