<?php
declare(strict_types=1);

namespace CakephpTwilio\Controller\Component;

use Cake\Controller\Component;
use Cake\Core\Configure;
use CakephpTwilio\Model\Message;
use Twilio\Exceptions\ConfigurationException;
use Twilio\Rest\Client;

/**
 * Twilio component
 */
class TwilioComponent extends Component
{
    /**
     * Default configuration.
     *
     * @var array
     */
    protected $_defaultConfig = [];

    /** @var Client */
    protected $twilioGateway;

    /**
     * @param array $config
     */
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        if ($this->twilioGateway == null) {
            try {
                $this->twilioGateway = new Client(Configure::read('Twilio.Sid'), Configure::read('Twilio.Token'));
            } catch (ConfigurationException $e) {
                // TODO
            }
        }
    }

    /**
     * Send message with Twilio Gateway
     * @param string $to
     * @param array $data
     * @throws \Twilio\Exceptions\TwilioException
     */
    public function send(Message $message)
    {
        $this->twilioGateway->messages->create(
            $message->getTo(),
            [
                'from' => $message->getFrom(),
                'body' => $message->getBody()
            ]
        );
    }
}
